### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by qexat** [ChasJC23/Algebruh#1]
# 📌️ Todo List

## Improvements

- [ ] Expression factorisation for polynomials
- [x] Implement operators to allow expressions to be extended through simple arithmetic.
- [x] Fix up inconsistencies within `__str__` and `__repr__`
- [x] Implement derivatives for the remaining functions
- [x] Upgrade variable substitution to expression substitution
- [x] Allow non-parsed expressions in expression substitution
- [x] Replace partial expression with substitution
- [ ] Supply multiple different numerical types

### Optional

- [ ] Hide node type from user, use `Expression` alias instead (?)

## Optimization

- [ ] Use of functional identities for expression simplification
- [ ] Design algorithm for product simplification (e.g `x*x*x*x` → `x**4`)
